package nx.zsanchez.nexussecurity.util;

import java.security.SecureRandom;

/**
 * Utilities for the plugin's API key format.
 * Keys follow the pattern {@code sk-} followed by 24 characters from [A-Za-z0-9].
 * The same format is generated by the external key generator web app.
 */
public final class ApiKeyUtil {

    private static final String ALPHABET =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private static final int LENGTH = 24;

    private static final SecureRandom RNG = new SecureRandom();

    private ApiKeyUtil() {}

    /** Generates a new API key in the canonical {@code sk-XXXXXXXXXXXXXXXXXXXXXXXX} format. */
    public static String generate() {
        StringBuilder sb = new StringBuilder("sk-");
        for (int i = 0; i < LENGTH; i++) {
            sb.append(ALPHABET.charAt(RNG.nextInt(ALPHABET.length())));
        }
        return sb.toString();
    }

    /** Returns true if the string matches the canonical API key format. */
    public static boolean isValidFormat(String key) {
        if (key == null) return false;
        if (key.length() != 3 + LENGTH) return false;
        if (!key.startsWith("sk-")) return false;
        for (int i = 3; i < key.length(); i++) {
            char c = key.charAt(i);
            if (ALPHABET.indexOf(c) < 0) return false;
        }
        return true;
    }
}
