[build]
  publish = "."
  functions = "netlify/functions"

# Instala automáticamente las dependencias declaradas en netlify/functions/package.json
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/v1/validate"
  to = "/.netlify/functions/validate"
  status = 200
  force = true

[[redirects]]
  from = "/v1/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true
